# ============================================================
# app.properties
# Параметри підключення до бази даних PostgreSQL
# ============================================================

db.url=jdbc:postgresql://localhost:5432/employee
db.user=postgres
db.password=313177
